[project]
name = "learnhub"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "minhchi972000", email = "95021191+minhchi972000@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.142.2",
    "psycopg[binary]>=3.2",
    "pydantic>=2.13.5",
    "pyyaml>=6.0.3",
    "sqlmodel>=0.0.47",
    "uvicorn[standard]>=0.54.0",
]

[project.scripts]
learnhub = "learnhub:main"

[build-system]
requires = ["uv_build>=0.11.7,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
]
